######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "C:/Users/SI/osc/osc.srcs/sources_1/edk/osc"
if { [xload new osc.xmp] != 0 } {
  exit -1
}
xset arch spartan6
xset dev xc6slx45
xset package csg324
xset speedgrade -3

xset binfo 

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl verilog
save proj
exit
